server:
  port: 9009

spring:
  datasource:
    url: jdbc:mysql:///hrm-user?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
hrm:
  swagger:
    title: 用户管理服务
    description: 用户管理服务接口